### ISSUE TITLE
Keygen is not defined

### ISSUE THREAD

**Issue by plazav** [EOSIO/eosjs-keygen#12]
Trying to add eosjs-keygen to Angular project. Eosjs and eosjs-api are already added.
Code is looking like:
```
declare var Keygen: any
declare var Keystore: any
import { Keystore, Keygen } from 'eosjs-keygen'
//…
Keygen.generateMasterKeys().then(keys => {
    console.log(keys)
  })
```
I have tried different ways to do it, but same result: "ReferenceError: Keygen is not defined".
Have tried also generate eosjs-keygen.js file and use it with simple html page. Same result.
Help needed or some more documentation.

UPDATE:
Keygen is also missing there:
`var {format, api, ecc, json, Fcbuffer} = Eos.modules`

Probably it could be taken somehow from eos initialization.

**Comment by jcalfee** [comment]
Most projects do not need keygen so we don't want to bloat eosjs..  You probably do not need keygen..   

Can you tell me more about what you want to do?

**Comment by jcalfee** [comment]
Kegen is another package: `npm install eosjs-keygen`

You may want to review and make sure that is what you want, this is pretty straight forward:
https://github.com/EOSIO/eosjs-keygen/blob/master/src/keygen.js#L34-L59

The only thing I would change, is if the master password is backed up by the user, I would use a  bip39 mnemonic phrase instead of the master password.  Users try to write down base58 and get the case mix-up .. bip39 fixes this.  It is possible to convert a master password to / from a mnemonic phrase.

**Comment by plazav** [comment]
Yes, you right. Probably it is not needed and keys could be generated with ecc. Anyway, thank you for quick answer!
